
package Interface;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Zelec
 */
public class MensajeOculto extends javax.swing.JFrame {

 
    String Mensaje = "<html><body>"
            + "<p>"
            + "En Pragmatic Morphoide hay mas que solo cursos<br>"
            + "Ten eso En cuenta y Resuelve El misterio<br>"
            + "</p>"
            + "</html></body>";
    
    public MensajeOculto() {

        initComponents();

    }

    public void CerrandoMensaje() {
        
        try {
            Thread.sleep(3500);
            this.setVisible(false);
        } catch (InterruptedException ex) {
            Logger.getLogger(MensajeOculto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Inicio = new java.awt.Panel();
        Logo = new javax.swing.JLabel();
        Marca = new javax.swing.JLabel();
        MEnsaje = new javax.swing.JLabel();
        m = new javax.swing.JLabel();
        Contenedor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoAzulado.png"))); // NOI18N
        Logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Inicio.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 24, 24));

        Marca.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        Marca.setForeground(new java.awt.Color(255, 255, 255));
        Marca.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Marca.setText("By Etherias Projects");
        Marca.setToolTipText("");
        Inicio.add(Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 100, 20));

        MEnsaje.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        MEnsaje.setForeground(new java.awt.Color(255, 255, 255));
        MEnsaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MEnsaje.setText("Haz Descubierto el mensaje Oculto");
        Inicio.add(MEnsaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 240, 30));

        m.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        m.setForeground(new java.awt.Color(255, 255, 255));
        m.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m.setText(Mensaje);
        Inicio.add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 380, 70));

        Contenedor.setBackground(new java.awt.Color(102, 102, 102));
        Contenedor.setForeground(new java.awt.Color(255, 255, 255));
        Contenedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Royal.png"))); // NOI18N
        Inicio.add(Contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 190));

        getContentPane().add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MensajeOculto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MensajeOculto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MensajeOculto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MensajeOculto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MensajeOculto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contenedor;
    private java.awt.Panel Inicio;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel MEnsaje;
    private javax.swing.JLabel Marca;
    private javax.swing.JLabel m;
    // End of variables declaration//GEN-END:variables
}
